### ISSUE TITLE
How to start it?

### ISSUE THREAD

**Issue by epirus** [Joker316701882/Deep-Image-Matting#16]
├── model
│   ├── checkpoint.dms
│   ├── model.ckpt-3200.data-00000-of-00001
│   └── model.ckpt-3200.index

Get Error

File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1662, in restore
    raise ValueError("Can't load save_path when it is None.")

How to start it ?

**Comment by LiangliangGuo** [comment]
Hi, Have you got how to start it? can you tell me ?
